type=page
status=published
title=create-threadpool
next=create-transport.html
prev=create-system-properties.html
~~~~~~

= create-threadpool

[[create-threadpool]]

== create-threadpool

Adds a thread pool

=== Synopsis

[source]
----
asadmin [asadmin-options] create-threadpool [--help]
[--target target]
[--maxthreadpoolsize maxthreadpoolsize]
[--minthreadpoolsize minthreadpoolsize]
[--idletimeout idletimeout] [--maxqueuesize maxqueuesize]
[--workqueues workqueues] [--classname classname]
[--virtual virtual] threadpool-id
----

=== Description

The `create-threadpool` subcommand creates a thread pool with the
specified name. You can specify maximum and minimum number of threads in
the pool, the quantity of messages, and the idle timeout of a thread.
The created thread pool can be used for servicing IIOP requests and for
resource adapters to service work management requests. A thread pool can
be used in multiple resource adapters.

This subcommand is supported in remote mode only.

=== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:asadmin.adoc#asadmin[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target on which you are creating the thread pool.
  Valid values are as follows:

  `server`;;
    Creates the thread pool for the default {productName} instance
    `server` and is the default value
  configuration-name;;
    Creates the thread pool for the named configuration.
  cluster-name;;
    Creates the thread pool for every instance in the cluster.
  instance-name;;
    Creates the thread pool for a particular instance.

`--maxthreadpoolsize`::
  Specifies the maximum number of threads the pool can contain. Default is 5.
`--minthreadpoolsize`::
  Specifies the minimum number of threads in the pool. These are created
  when the thread pool is instantiated. Default is 2.
`--idletimeout`::
  Specifies the amount of time in seconds after which idle threads are
  removed from the pool. Default is 900.
`--maxqueuesize`::
  Specifies the maximum number of messages that can be queued until
  threads are available to process them for a network listener or IIOP
  listener. A value of -1 specifies no limit. Default is 4096.
`--workqueues`::
  Do not specify this option. This option is retained for compatibility
  with earlier releases. If you specify this option, a syntax error does
  not occur. Instead, the subcommand runs successfully and displays a
  warning message that the option is ignored.
`--classname`::
  Specifies the fully qualified class name of a custom thread pool implementation.
  If not specified, the default thread pool implementation will be used.
`--virtual`::
  Specifies whether to use virtual threads for the thread pool. When set to
  `true`, the thread pool will use virtual threads. When set to `false` (default), 
  the thread pool will use platform threads. This setting applies when using the 
  default thread pool implementation (when classname is not specified or is set to 
  the default value). When a custom classname is specified, this setting is ignored. 
  Default is `false`.

=== Operands

threadpool-id::
  An ID for the work queue, for example, `threadpool-1`.

=== Examples

[[sthref558]]

==== Example 1   Creating a Thread Pool

This command creates a new thread pool called `threadpool-l` that uses platform threads (the default).

[source]
----
asadmin> create-threadpool --maxthreadpoolsize 100
--minthreadpoolsize 20 --idletimeout 2 threadpool-1
Command create-threadpool executed successfully
----

[[sthref559]]

==== Example 2   Creating a Thread Pool with Virtual Threads Enabled

This command creates a new thread pool called `threadpool-2` that uses virtual threads.

[source]
----
asadmin> create-threadpool --maxthreadpoolsize 50
--minthreadpoolsize 10 --virtual true threadpool-2
Command create-threadpool executed successfully
----

[[sthref560]]

==== Example 3   Creating a Thread Pool with Custom Implementation

This command creates a new thread pool called `threadpool-3` with a custom thread pool implementation.

[source]
----
asadmin> create-threadpool --maxthreadpoolsize 75
--classname com.example.CustomThreadPool threadpool-3
Command create-threadpool executed successfully
----

=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

=== See Also

xref:asadmin.adoc#asadmin[`asadmin`(1M)]

xref:delete-threadpool.adoc#delete-threadpool[`delete-threadpool`(1)],
xref:list-threadpools.adoc#list-threadpools[`list-threadpools`(1)]
