name: Build on MacOS

on:
  pull_request:
    branches:
    - "master"
    - "8.0"

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      # qa skips documentation - we check it on Jenkins CI
      # We skip checkstyle too - we check it on Jenkins CI
      run: mvn -B -e -ntp install -Pstaging -Pqa '-Dcheckstyle.skip=true' -Pfastest
    - name: Test Starts
      run: mvn -B -e -ntp install -Pstaging '-Dcheckstyle.skip=true' -pl :glassfish-itest-tools
